name: Deploy to EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: maven

      - name: Build JAR file
        run: mvn clean install -B package --file pom.xml

      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ec2-3-72-60-197.eu-central-1.compute.amazonaws.com
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: target/*.jar
          target: /home/ubuntu
          script: |
            export DB_PASSWORD=${aws ssm get-parameters --names DB_PASSWORD --query Parameters[0].Value --with-decryption) 
            java -jar /home/ubuntu/target/demo-0.0.1-SNAPSHOT.jar

      - name: Connect to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-72-60-197.eu-central-1.compute.amazonaws.com
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script:
            ps;


#  sudo systemctl stop demo
#  sudo cp /home/ubuntu/demo.jar /opt/demo/demo.jar
# sudo systemctl start demo
